### PR TITLE
Random: Replaced factories.array with DNDarray

### PR DESCRIPTION
**Pull request by shahpratham**
## Description

Replaced factories.array with DNDarray in random.py
Issue/s resolved: #800 

## Changes proposed:
- factories.array -> dndarray.DNDarray

## Type of change

enhancement

## Due Diligence
- [ ] All split configurations tested
- [ ] Multiple dtypes tested in relevant functions
- [ ] Documentation updated (if needed)
- [ ] Updated changelog.md under the title "Pending Additions"

#### Does this change modify the behaviour of other functions? If so, which?
no

### CODE REVIEW

**Comment by mtar** [comment]
GPU cluster tests are currently disabled on this Pull Request.

**Comment by shahpratham** [comment]
@ClaudiaComito  @mtar  Please tell if any changes are required.

**Review by mtar — CHANGES_REQUESTED** [review]
Please, also look at the [comments](https://github.com/helmholtz-analytics/heat/pull/949#issuecomment-1086194240) @ClaudiaComito wrote in the similar PRs #949 and #951 for more tips.

**Comment by shahpratham** [comment]
@mtar I have made some changes, could be please review.

**Comment by mtar** [comment]
Thank you very much @shahpratham, this looks better now.

**Comment by ClaudiaComito** [comment]
run tests

**Review by ClaudiaComito — COMMENTED** [review]
Thanks a lot @shahpratham ! Can you update the CHANGELOG?

**Review by ClaudiaComito — APPROVED** [review]
Well done @shahpratham !

**Comment by ClaudiaComito** [comment]
run tests

**Pull request merged**
