### PR TITLE
Features/538 larray

### PR DESCRIPTION
**Pull request by lenablind**
## Description

Introduction of property `larray`, which allows access to the underlying local torch tensor (`_DNDarray__array` / `__array` attribute of `DNDarray`).
For the setter, I included a warning as requested in the issue.

Consequently, I replaced all usages of `_DNDarray__array` within the project space with `larray`. 

As I specified torch.tensor as the only valid dtype for this attribute, I had to adapt function `average` in statistics, simply wrapping a float assignment into a tensor containing that specific float (just one line (328) modified).

Issue/s resolved: #538

## Changes proposed:
- Introduction of property `larray` in dndarray
- replacement of all usages of `_DNDarray__array` with `larray` within the project space
- Corresponding tests (especially for the setter)
- Minimal adaption of function `average` in statistics (line 328)

## Type of change
- New feature (non-breaking change which adds functionality)

## Due Diligence

- [x] All split configurations tested
- [x] Multiple dtypes tested in relevant functions
- [x] Documentation updated (if needed)
- [x] Updated changelog.md under the title "Pending Additions"

#### Does this change modify the behaviour of other functions? If so, which?
no (, not after the presented modification of `average` in statistics. Without the wrapping, a TypeError is thrown as specified in the setter of `larray`, which expected a torch.tensor but got a float (in the corresponding tests) instead).

### CODE REVIEW

**Comment by Markus-Goetz** [comment]
Outstanding job Lena. As far as I can see, our core is now issuing a lot of warning. As per issue that was asked for. However, I feel, that I should modify this as to: if the user is using the larray setter a warning should be issued, if the core is using larray, then warnings should be suppressed, as we are supposedly know what we are doing. Do you think you can change it to be that way? Or do you have differing thoughts?

**Comment by lenablind** [comment]
> Outstanding job Lena. As far as I can see, our core is now issuing a lot of warning. As per issue that was asked for. However, I feel, that I should modify this as to: if the user is using the larray setter a warning should be issued, if the core is using larray, then warnings should be suppressed, as we are supposedly know what we are doing. Do you think you can change it to be that way? Or do you have differing thoughts?

Thank you, Markus. Yes, I agree, this sounds reasonable to me. I'll try to change it to be that way.

**Review by coquelin77 — APPROVED** [review]

**Comment by coquelin77** [comment]
@lenablind can you handle the merge here? there is some minor conflicts with the `nbytes` feature

**Comment by lenablind** [comment]
> @lenablind can you handle the merge here? there is some minor conflicts with the `nbytes` feature

@coquelin77 Yes for sure! Thank you for taking care of this and the previous PRs

**Review by coquelin77 — APPROVED** [review]

**Pull request merged**
