### PR TITLE
Features/584 data parallel

### PR DESCRIPTION
**Pull request by coquelin77**
## Description

Implementation of Data Parallel Neural Networks. Documentation about how to use in still being written. This is still not a final iteration, there are many things which will be tuned in the background. 

Issue/s resolved: #584 #585 #603 #604 #605 #606 

## Changes proposed:
- Implement `DataParallel` class
- Implement `DataLoader` class
- Implement `Dataset` class (template)
- call through to `torch.nn` modules and `torch.nn.functional` routines
- Added MNIST example as a working data parallel NN to examples/nn/mnist
- `MNISTDataset` added for loading data and preparing for the network architecture 
- Image-net example added
- Partial data loading from an HDF5 file is made available with an iterator and dataset class.

## Type of change
- New feature (non-breaking change which adds functionality)
- Documentation update

## Due Diligence

- [ ] ~~All split configurations tested~~
- [x] Multiple dtypes tested in relevant functions
- [ ] Documentation updated (if needed)
- [ ] Updated changelog.md under the title "Pending Additions"

#### Does this change modify the behaviour of other functions? If so, which?
no

#### Notes
There will be backend changes for efficiency coming in the future. however, this feature is becoming rather large and a review/merge would make it more manageable in the future
* changelog still to be fixed!

### CODE REVIEW

**Comment by mtar** [comment]
GPU cluster tests are currently disabled on this Pull Request.

**Comment by coquelin77** [comment]
the coverage is what its going to be. there are about 35 lines which wont be touched without very very extensive tests to hit the very specific cases, if at all

**Comment by mtar** [comment]
ok to test

**Comment by mtar** [comment]
rereun tests

**Comment by mtar** [comment]
run dev tests

**Comment by mtar** [comment]
run pre tests

**Comment by mtar** [comment]
run pre tests

**Comment by mtar** [comment]
run dev tests

**Comment by mtar** [comment]
run pre tests

**Comment by mtar** [comment]
run dev tests

**Comment by mtar** [comment]
run pre tests

**Comment by coquelin77** [comment]
This branch is updated and the tests run clean. there is no way to increase the coverage for this branch without overhauling how coverage is reported. 

It is also important to note that since this development, there have been many improvements to the data parallel neural networks which builds on these addition. If there are questions / comments for this PR I will give it until the end of the year, then it will be merged into the master. I apologize for the length of this PR as well. The length was unavoidable for this feature

**Comment by coquelin77** [comment]
rerun tests

**Comment by coquelin77** [comment]
rerun tests

**Comment by coquelin77** [comment]
this is going to be forced in. Other changes are waiting and can be made on the fly

**Pull request merged**
