### PR TITLE
Using global default comm in load_csv

### PR DESCRIPTION
**Pull request by fschlimb**
Issue/s resolved: #833 

## Type of change
bugfix

### CODE REVIEW

**Comment by mtar** [comment]
GPU cluster tests are currently disabled on this Pull Request.

**Review by coquelin77 — APPROVED** [review]

**Comment by coquelin77** [comment]
run tests

**Comment by coquelin77** [comment]
we are experiencing issues with our GPU testing on the system at the moment. We are working on it and have asked the sysadmins about it. hopefully this is fixed shortly.

**Comment by coquelin77** [comment]
rerun tests

**Pull request merged**
