### PR TITLE
Features/560 reshape speedup

### PR DESCRIPTION
**Pull request by ClaudiaComito**
## Description

While testing Heat+torch 2.0 on Apple MPS #1053 I noticed a major bottleneck in `ht.reshape`  even on 1 process. We had been discussing this some time ago, #560, #874

The main slow-down arises in setting up  the `Alltoallv` communication necessary when the input DNDarray is distributed along non-zero axes (`ht.reshape(x, new_shape, new_split)` with `x.split > 0` and potentially `new_split >0`). 

I ran some experiments and realized that resplitting in place (input split to 0, and then if necessary 0 to new_split) while inelegant still performs much better than the  current implementation. This PR implements a pragmatic solution based on `dndarray.resplit_` and `dndarray.redistribute_`.

~~Below some plots from tests on my laptop - matrices are still relatively small and 1-process performance is still better than 2-processes, will replace with scaling tests on HDF ML later.~~

**UPDATED**

Below some tests run on HDF ML, CPU only, 2 CPUs per node, 12 threads per CPU. 
Initial matrix: `A = ht.zeros((1000, size), split=key[0])`
Timed operation: `B = ht.reshape(A, (10000000, -1), new_split=key[1])`
Sampled sizes: `sizes = [500000*n for n in [1, 2, 4, 8, 16, 32, 64, 128, 256]]`
Sampled split combinations: `[[0, 0], [1, 1], [1, 0], [0, 1]]` (only showing plots for  split combi 0-0, 1-1) 
Minimum speed-up: ~8.5 for split 0-0, ~3 for split 1-1 which requires more communication.

reshape_weak

reshape_strong_8x

reshape_strong_64x

Issue/s resolved: #560, #874 

## Changes proposed:
- replace `Alltoallv` call with resplitting in place when necessary
-  updated documentation
-
-

## Type of change

Performance enhancement
## Memory requirements

In progress
## Performance

In progress, also see plots

## Due Diligence
- [x] All split configurations tested
- [x] Multiple dtypes tested in relevant functions
- [x] Documentation updated (if needed)
- [x] Title of PR is suitable for corresponding CHANGELOG entry

#### Does this change modify the behaviour of other functions? If so, which?
no

### CODE REVIEW

**Review by mrfh92 — APPROVED** [review]
These changes look fine to me.

**Comment by mrfh92** [comment]
I can run the additional scaling tests

**Comment by ClaudiaComito** [comment]
> 

Hi @mrfh92 , thanks for the review, I actually ran the scaling tests of this implementation. I will run comparison tests with the released `reshape` as well.

**Comment by mrfh92** [comment]
**Strong scaling for a short-fat matrix and split=0,1** 

reshape_main_cpu
reshape_main_gpu
reshape_new_cpu
reshape_new_gpu

**Strong scaling for different shapes from short-fat to tall-skinny (split=1 only)** 

reshape_main_cpu
reshape_main_gpu
reshape_new_cpu
reshape_new_gpu

**Comment by mrfh92** [comment]
It looks like that the "old" reshape is significantly slower than the "new" one (in particular for a small number of processes), but the "old" reshape scales well when increasing the number of processes; the "new" reshape does not seem to scale well (which is expected, because resplit will always have runtime proportional to the number of processes...)

**Comment by ClaudiaComito** [comment]
> It looks like that the "old" reshape is significantly slower than the "new" one (in particular for a small number of processes), but the "old" reshape scales well when increasing the number of processes; the "new" reshape does not seem to scale well (I believe that is due to the usage of resplit which will always have runtime proportional to the number of processes...)
> 
> Nevertheless, this does not necessarily imply that the "new" reshape is not an improvement compared to the "old" one; in contrary, the "new" version is that much more faster for small number of processes that it stil outperforms the "old" one there. However, there we should determine whether there is some break-even point at which the "old" one becomes better.

Thanks a lot @mrfh92 for all the tests. I went back and finished the tests I had started on the cluster, adding test runs on the release (`main` branch) version of reshape. I've updated the PR description with plots and more details on the experiments.

**Review by mrfh92 — APPROVED** [review]
The new plots in the PR description show that my worries on possible performance degradation w.r.t. scalability were actually unjustified. Therefore, I now recommend merging if the CI runs through.

**Pull request merged**
