### PR TITLE
Fix finding spectral gap with identical diffs

### PR DESCRIPTION
**Pull request by sebimarkgraf**
Issue/s resolved: #715

## Changes proposed:
- Change to argmax to prevent multiple identical diffs crashing the algorithm

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## Due Diligence
- [X] All split configurations tested (tested in test_spectral already)
- [X] Multiple dtypes tested in relevant functions (tested in test_spectral already)
- [X] Updated changelog.md under the title "Pending Additions"

#### Does this change modify the behaviour of other functions? If so, which?
no

### CODE REVIEW

**Comment by mtar** [comment]
GPU cluster tests are currently disabled on this Pull Request.

**Comment by mtar** [comment]
GPU cluster tests are currently disabled on this Pull Request.

**Comment by mtar** [comment]
GPU cluster tests are currently disabled on this Pull Request.

**Review by coquelin77 — DISMISSED** [review]

**Comment by coquelin77** [comment]
run tests

**Review by coquelin77 — APPROVED** [review]

**Comment by mtar** [comment]
test this once

**Comment by mtar** [comment]
test this once

**Pull request merged**
