### PR TITLE
Resolved PyTorch meshgrid warning and indexing issue in `heat.meshgrid`

### PR DESCRIPTION
**Pull request by samadpls**
## Due Diligence

- General:
    - [X]  **base branch** must be `main` for new features, latest release branch (e.g. `release/1.3.x`) for bug fixes
    - [X]  **title** of the PR is suitable to appear in the [Release Notes](https://github.com/helmholtz-analytics/heat/releases/latest)
- Implementation:
    - [X] unit tests: all split configurations tested
    - [X] unit tests: multiple dtypes tested
    - [X] documentation updated where needed

## Description
Resolved PyTorch warning in `heat.meshgrid` and updated indexing for compatibility

Issue/s resolved: #1231 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

#### Does this change modify the behaviour of other functions? If so, which?
no

### CODE REVIEW

**Comment by mrfh92** [comment]
Both the tests on AMD- and Nvidia-Hardware failed at `meshgrid` (see above under "ci/codebase — The build failed! " -> "Details")

**Comment by samadpls** [comment]
Thank you @mrfh92 for bringing the test failures to my attention. I've reviewed the local test output, and it's not matching the errors in the 'ci/codebase' environment. I'm currently investigating the issue but I'd also appreciate any additional insights or suggestions you might have.

These are what I'm getting while running locally:

### unittest
image

### pytest
image

### Individually running
```python
DNDarray([[[0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.]],

          [[2., 2., 2., 2., 2.],
           [2., 2., 2., 2., 2.],
           [2., 2., 2., 2., 2.]],

          [[4., 4., 4., 4., 4.],
           [4., 4., 4., 4., 4.],
           [4., 4., 4., 4., 4.]]], dtype=ht.float32, device=cpu:0, split=0) xx
DNDarray([[[0., 1., 2., 3., 4.],
           [0., 1., 2., 3., 4.],
           [0., 1., 2., 3., 4.]],

          [[0., 1., 2., 3., 4.],
           [0., 1., 2., 3., 4.],
           [0., 1., 2., 3., 4.]],

          [[0., 1., 2., 3., 4.],
           [0., 1., 2., 3., 4.],
           [0., 1., 2., 3., 4.]]], dtype=ht.float32, device=cpu:0, split=0) yy
DNDarray([[[0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
           [0.5000, 0.5000, 0.5000, 0.5000, 0.5000],
           [1.0000, 1.0000, 1.0000, 1.0000, 1.0000]],

          [[0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
           [0.5000, 0.5000, 0.5000, 0.5000, 0.5000],
           [1.0000, 1.0000, 1.0000, 1.0000, 1.0000]],

          [[0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
           [0.5000, 0.5000, 0.5000, 0.5000, 0.5000],
           [1.0000, 1.0000, 1.0000, 1.0000, 1.0000]]], dtype=ht.float32, device=cpu:0, split=0) zz

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]]

 [[4. 4. 4. 4. 4.]
  [4. 4. 4. 4. 4.]
  [4. 4. 4. 4. 4.]]] res_xx
[[[0. 1. 2. 3. 4.]
  [0. 1. 2. 3. 4.]
  [0. 1. 2. 3. 4.]]

 [[0. 1. 2. 3. 4.]
  [0. 1. 2. 3. 4.]
  [0. 1. 2. 3. 4.]]

 [[0. 1. 2. 3. 4.]
  [0. 1. 2. 3. 4.]
  [0. 1. 2. 3. 4.]]] res_yy
[[[0.  0.  0.  0.  0. ]
  [0.5 0.5 0.5 0.5 0.5]
  [1.  1.  1.  1.  1. ]]

 [[0.  0.  0.  0.  0. ]
  [0.5 0.5 0.5 0.5 0.5]
  [1.  1.  1.  1.  1. ]]

 [[0.  0.  0.  0.  0. ]
  [0.5 0.5 0.5 0.5 0.5]
  [1.  1.  1.  1.  1. ]]] res_zz
True
True
True
```
### code 
```python
import heat as ht
import numpy as np

x = ht.linspace(0, 4, 3)
y = ht.linspace(0, 4, 5)
z = ht.linspace(0, 1, 3, split=0)

zz, xx, yy = ht.meshgrid(z, x, y)
res_zz, res_xx, res_yy = np.meshgrid(z.numpy(), x.numpy(), y.numpy())
print(xx,"xx")
print(yy,"yy")
print(zz,"zz")

print()
print(res_xx,"res_xx")
print(res_yy,"res_yy")
print(res_zz,"res_zz")
print(ht.equal(xx, ht.array(res_xx)))
print(ht.equal(yy, ht.array(res_yy)))
print(ht.equal(zz, ht.array(res_zz))
```

**Comment by mrfh92** [comment]
Hi @samadpls, 
did you run the tests serial or in parallel? 
You can run them in parallel using, e.g.,  
```
cd heat
mpirun -n 2 python -m unittest -vf /heat/core/tests/test_manipulations.py
```
for running on 2 cores in parallel. You can replace `2` by another number as long as your machine has sufficiently many cores. If you want to test for a higher number of processes than your machine has cores, you can use 
```
mpirun -n 20 --oversubscribe python ... 
```
which then makes MPI acting as if there were suffciently many cores. Of course, then there will no positive effect of parallelization w.r.t. runtime any more; instead, the code will even get slower, but you will still be able to find errors.

**Comment by mrfh92** [comment]
Another remark: in the case your machine has a GPU that allows for CUDA, you can run the tests on GPU by 
```
HEAT_TEST_USE_DEVICE=gpu mpirun ...
```
(but I dont think that this is necessary for debugging)

**Comment by samadpls** [comment]
Hi @mrfh92 ,

Thanks for the suggestion and feedback. I did try running the tests in parallel, but I encountered an issue with the `ht.meshgrid` function when using two cores. It seems that the function returns an unexpected result. Here's the output I received:

```
[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],
        [[2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.]],
        [[4., 4., 4., 4., 4.],
         [4., 4., 4., 4., 4.]]]
```

I was expecting:

```
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]],
 [[2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]],
 [[4. 4. 4. 4. 4.]
  [4. 4. 4. 4. 4.]
  [4. 4. 4. 4. 4.]]]
```

I also attempted to use the `ht.allclose` method to compare the results, but unfortunately, this led to a segmentation fault (SIGABRT).

I've been debugging this test failure for a while now, but I haven't been able to resolve it. I suspect there might be an issue with the `ht.meshgrid` function when running tests in parallel. If you have any insights or suggestions on how to address this problem, I would greatly appreciate your assistance.

**Comment by samadpls** [comment]
@mrfh92 , I've been debugging for a while, and the test only passes when `split` is set to `None`. I'm not sure what's causing this. Any suggestions would be appreciated. Thanks!

**Comment by samadpls** [comment]
@mrfh92, the issue was elsewhere in the code. The latest merge has successfully resolved it, and all tests have passed. Kindly review it.

**Pull request closed without merging**
