### PR TITLE
Add solver for triangular systems

### PR DESCRIPTION
**Pull request by FOsterfeld**
Copy of the previous PR for solve_triangular #1236 .

to add the context: we had already merged this PR, but then some error with the CI occurred and undid the changes (which were, however, not responsible for this error as we found out later)

### CODE REVIEW

**Comment by mrfh92** [comment]
to add the context: we had already merged this PR, but then some error with the CI occurred and undid the changes (which were, however, not responsible for this error as we found out later)

**Review by ClaudiaComito — APPROVED** [review]
Thanks for resubmitting!

**Review by ClaudiaComito — CHANGES_REQUESTED** [review]
@FOsterfeld apologies, I just noticed the lines that aren't covered by tests, can we increase the test coverage?

**Review by ClaudiaComito — APPROVED** [review]
Great @FOsterfeld thanks for the changes!

**Pull request merged**
