### PR TITLE
Added automatic docstring linting

### PR DESCRIPTION
**Pull request by rainman110**
## Description

This PR introduces docstring linting. The linter "pydocstyle" checks, whether docstring are missing, paramters are all documented and so on.
I already disabled many errors, but there are still many to be fixed.

Issue/s resolved: #588 

## Changes proposed:
- Added pydocstyle configuration
- Added git pre-commit hook to automatically check the docstrings

## Type of change
 - Change software engineering process
 - CI change

## Due Diligence

- [ ] Documentation updated (if needed)
- [ ] Updated changelog.md under the title "Pending Additions"

#### Does this change modify the behaviour of other functions? If so, which?
no

### CODE REVIEW

**Comment by rainman110** [comment]
I noticed, that the checker also currently checks the ``tests`` folders. I suppose we don't want this.

There's a way to configure pydocstyle to filter file and folder via the `` --match-dir=<pattern>`` regex:  
http://www.pydocstyle.org/en/stable/usage.html#command-line-interface

I am no expert for regexes, in particular if we want to exclude thing, not include:
 **Does anyone know how to configure it properly to exlude tests?**

**Comment by rainman110** [comment]
@Markus-Goetz This PR is idling. Can anyone have a look?

**Comment by coquelin77** [comment]
did you ever create the proper config file to ignore the test folders? it looks like it is in a config file in the link that you sent

**Comment by rainman110** [comment]
The config is stored in setup.cfg

**Comment by coquelin77** [comment]
i thought that you said it was still checking the tests folders and we wanted to ignore that

**Comment by coquelin77** [comment]
ive added the exclusion for the test. @Cdebus is in charge of the docstring formatting branch so they are the best person to look over the implications of this PR. I have tagged her as a reviewer here

**Comment by Cdebus** [comment]
All Checks are failing, hence I did not look at the PR so far

**Review by Cdebus — COMMENTED** [review]
Ok, glancing over the build, this will be a nightmare to fix before all our docstrings go through. This is something to be tackled by everyone, i.e we should discuss that everyone makes sure about their assigned files that they adhere to this.
Also, I have some concerns, whether this goes with our new Doc Style Guideline. As in: There is a lot off errors for e.g missing docstrings in ``__init__`` functions or for private attributes. **Is there a way to configure this more customary?** Those are not shown in the build documentation (I configured sphinx for that), and there was a lot of discussion whether private functions should have docstrings. Otherwise, we need to discuss this in the sprint planning

**Comment by coquelin77** [comment]
> Ok, glancing over the build, this will be a nightmare to fix before all our docstrings go through. This is something to be tackled by everyone, i.e we should discuss that everyone makes sure about their assigned files that they adhere to this.
> Also, I have some concerns, whether this goes with our new Doc Style Guideline. As in: There is a lot off errors for e.g missing docstrings in `__init__` functions or for private attributes. **Is there a way to configure this more customary?** Those are not shown in the build documentation (I configured sphinx for that), and there was a lot of discussion whether private functions should have docstrings. Otherwise, we need to discuss this in the sprint planning

there are some config options but they are limited. i forced it to ignore the test folders and in principle this can also be done for the init files but they have to be added individually. i didnt see an option for a wildcard character

**Pull request merged**
