### PR TITLE
adding square

### PR DESCRIPTION
**Pull request by fschlimb**
Adding square.
Just a monkey-coded cut&paste&edit from sqrt.

### CODE REVIEW

**Comment by mtar** [comment]
GPU cluster tests are currently disabled on this Pull Request.

**Comment by coquelin77** [comment]
run tests

**Review by coquelin77 — APPROVED** [review]
Looks good to me. Thanks for the function!

**Comment by mtar** [comment]
ok to test

**Review by coquelin77 — APPROVED** [review]

**Pull request merged**
