### PR TITLE
Continuous benchmarks for linalg: try to separate data creation from the actual tests

### PR DESCRIPTION
**Pull request by mrfh92**
I tried to separate the creation of test data from the actual tests in the `linalg`-file of continuous benchmarking 
(see also #1157 )

For `reshape` I have no idea how to proceed so far...

### CODE REVIEW

**Comment by ClaudiaComito** [comment]
@mrfh92 I modified the reshape benchmark, do you think this works?

**Comment by mrfh92** [comment]
@ClaudiaComito I guess that this will work, however I am not sure whether we want to go the way to perform tests with several different shapes at once since in this case we cant know in the end which shape/size/split etc. contributes the most, both w.r.t. time (and possibly lateron memory as well). 

So Im not sure whether we should rather restrict timings always to a single case, i.e. one split and one shape instead of taking times together of a bunch of configurations.

**Comment by ClaudiaComito** [comment]
> @ClaudiaComito I guess that this will work, however I am not sure whether we want to go the way to perform tests with several different shapes at once since in this case we cant know in the end which shape/size/split etc. contributes the most, both w.r.t. time (and possibly lateron memory as well).
> 
> So Im not sure whether we should rather restrict timings always to a single case, i.e. one split and one shape instead of taking times together of a bunch of configurations.

You're right @mrfh92 . I'll not work on this for the next couple days. Let me know if you need me to do something.

**Comment by mrfh92** [comment]
@ClaudiaComito @JuanPedroGHM I think we should discuss this in the next project meeting, more precisely we should address the following question: how to choose a (hopefully) small set of illustrative and representative benchmark examples?

**Comment by mrfh92** [comment]
May be worth waiting for this until #1151 is finished and what kind of benchmarks we can run on the new runners

**Comment by mrfh92** [comment]
Actually, this issue is a bit more complicated: since we are sometimes working with randomly generated test data it might be useful to sample new test data for each measurement (if the runtime of a function depends on the actual data) ...

**Comment by mrfh92** [comment]
Actually, after having migrated the benchmark runs to gitlab I would suggest to use larger test data anyway (e.g. MNIST) ... so probably we should address recreating benchmarks then

**Comment by mrfh92** [comment]
I have just seen that this problem does not appear anymore in the current (main) version of the continuous benchmarks.

**Pull request closed without merging**
