### PR TITLE
fix #351: Solution 1: enforce weights.shape = x.shape for tuple axis

### LINKED ISSUE #351: ht.average() should allow weighted average across multiple axes
**Feature functionality**

`ht.average(x, weights=None, axis=None,  returned=False)` (PR #352) has the same constraints as numpy.average(), among them the following:

- if axis is not None, the weights tensor must be 1D and of the same size as x.gshape[axis].

This makes sense as long as axis is not a tuple. numpy.average() supports tuple axis, but as far as I understand, in this case np.average() only works if weights.shape = x.shape (this is not clear from the numpy documentation, it's what I gather from testing).

I see two possible solutions: 
1) enforce weights.shape = x.shape if axis is tuple (and make it clear in the docs)
2) allow weights = tuple of ht.tensors of the appropriate size and in the appropriate order for the respective axis.

At the moment, ht.average() raises a NotImplementedError if axis is a tuple.

### PR DESCRIPTION
**Pull request by Mystic-Slice**
Issue/s resolved: #351

## Type of change

Documentation update

## Due Diligence
- [ ] All split configurations tested
- [ ] Multiple dtypes tested in relevant functions
- [ ] Documentation updated (if needed)
- [ ] Updated changelog.md under the title "Pending Additions"

#### Does this change modify the behaviour of other functions? If so, which?
yes / no

skip ci

### CODE REVIEW

**Comment by mtar** [comment]
GPU cluster tests are currently disabled on this Pull Request.

**Review by ClaudiaComito — CHANGES_REQUESTED** [review]
@Mystic-Slice thanks a lot for taking this on and  welcome to our legacy code 😬 

I vaguely remember implementing `ht.average`, it seems so overly complicated now.

I agree with your solution 1, we can enforce - just like numpy - that `weights.shape == a.shape` if averaging along more than one axis. They must be distributed along the same split axis as well.

The distributed operation itself can be simplified quite a bit, as it's just:

`(a*weights).sum(axis)/weights.sum(axis)`

`a*weights` calls `_operations.__binary_op()` and `ht.sum()` calls `_operations.__reduce_op()`, those will take care of sanitizing, communication when needed, etc.

Please go ahead and make the changes whenever you feel comfortable. Thanks a lot!

**Comment by Mystic-Slice** [comment]
Hey @ClaudiaComito!
Sorry for the late reply!
I think the changes that you requested are already present in the code.
See lines 286 - 299

**Comment by Mystic-Slice** [comment]
Changes moved to a new branch. See, https://github.com/helmholtz-analytics/heat/pull/1037

**Pull request closed without merging**
