### PR TITLE
added duplicate comm

### PR DESCRIPTION
**Pull request by Dhruv454000**
## Description

Duplicate MPI_COMM_WORLD for the default communicator.

## Changes proposed:
 Added a duplicate of MPI_COMM_WORLD to make library more independent.

### CODE REVIEW

**Comment by mtar** [comment]
GPU cluster tests are currently disabled on this Pull Request.

**Comment by Dhruv454000** [comment]
@mtar any changes required?

**Comment by mtar** [comment]
Thank you. There is one minor issue: changelog.md needs to be updated under the title "Pending Additions". It might be useful to have a short comment in the code, too.

**Comment by Dhruv454000** [comment]
@mtar done with changes.

**Comment by Dhruv454000** [comment]
@mtar can you pls review.

**Comment by Dhruv454000** [comment]
@ClaudiaComito any changes are required?

**Comment by ClaudiaComito** [comment]
run tests

**Comment by ClaudiaComito** [comment]
@Dhruv454000 thanks a lot, I just started the tests on GPU, I think all checks will pass afterwards

**Comment by ClaudiaComito** [comment]
run tests

**Comment by ClaudiaComito** [comment]
run tests

**Comment by ClaudiaComito** [comment]
run tests

**Comment by ClaudiaComito** [comment]
run tests

**Comment by ClaudiaComito** [comment]
run tests

**Review by ClaudiaComito — APPROVED** [review]
Thanks a lot @Dhruv454000 for taking this on and congratulations on your first contribution here! 👏🏼

**Pull request merged**
