### PR TITLE
Features/torch1.7.0 update

### PR DESCRIPTION
**Pull request by mtar**
## Description

This PR fixes a few bugs when using PyTorch 1.7.

## Changes proposed:
- use pytorch equivalents on some NumPy functions (PyTorch 1.6 incompatibilities)
- keep logical shift in __threefry()
- adjust value in test_random

## Due Diligence

- [ ] All split configurations tested
- [ ] Multiple dtypes tested in relevant functions
- [ ] Documentation updated (if needed)
- [ ] Updated changelog.md under the title "Pending Additions"

#### Does this change modify the behaviour of other functions? If so, which?
yes / no

### CODE REVIEW

**Comment by mtar** [comment]
restart tests

**Comment by mtar** [comment]
run tests

**Comment by mtar** [comment]
run tests

**Review by coquelin77 — APPROVED** [review]
i removed the jitting for threefry32 to avoid the segfault which sometimes occurs on gpus. i will approve for now, pending the tests

**Comment by coquelin77** [comment]
rerun tests

**Comment by mtar** [comment]
rerun tests

**Comment by coquelin77** [comment]
this is passing, but there seems to be a failure in jenkins. the log shows it passing. im going to merge it

**Pull request merged**
