### PR TITLE
Fix `ht.diff` for 1-element-axis edge case

### PR DESCRIPTION
**Pull request by mtar**
## Due Diligence

- General:
    - [x]  **base branch** must be `main` for new features, latest release branch (e.g. `release/1.3.x`) for bug fixes
    - [x]  **title** of the PR is suitable to appear in the [Release Notes](https://github.com/helmholtz-analytics/heat/releases/latest)
- Implementation:
    - [x] unit tests: all split configurations tested
    - [x] unit tests: multiple dtypes tested
    - [x] documentation updated where needed

## Description

This Pull Request fixes two bugs where _diff()_ errors on an distributed array when the axis is size one and/or along the split axis.

Issue/s resolved: #753 

## Changes proposed:

- send the whole array if it is smaller then the hard index value 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

#### Does this change modify the behaviour of other functions? If so, which?
no

### CODE REVIEW

**Comment by ClaudiaComito** [comment]
Is this PR ready for review @mtar ?

**Comment by mtar** [comment]
We talked about it already and I marked it back as draft because we wanted to modernise the function. As things stand, however, the new implementation, that I was striving for, has more severe  bugs then the current one. 

The proposed changes were working the last time. I advise to merge the PR for now.

**Review by ClaudiaComito — APPROVED** [review]
Works fine, thanks a lot @mtar !

**Review by ClaudiaComito — APPROVED** [review]
Triggering CI matrix again after merging latest `release/1.3.x` changes

**Pull request merged**
