### PR TITLE
Fix two-process QR tests on CUDA runner

### PR DESCRIPTION
**Pull request by ClaudiaComito**
## Due Diligence

- General:
    - [x]  **base branch** must be `main` for new features, latest release branch (e.g. `release/1.3.x`) for bug fixes
    - [x]  **title** of the PR is suitable to appear in the [Release Notes](https://github.com/helmholtz-analytics/heat/releases/latest)
- Implementation:
    - [x] unit tests: all split configurations tested
    - [x] unit tests: multiple dtypes tested
    - [x] documentation updated where needed

## Description

Issue/s resolved: #1317

## Changes proposed:

- check for array distribution using `array.is_distributed()` to cover tests running on 1 MPI process
-
-
-

## Type of change

Bug fix
## Memory requirements

NA
## Performance

NA
#### Does this change modify the behaviour of other functions? If so, which?
no

### CODE REVIEW

**Comment by mrfh92** [comment]
Just as info: the last commit was a test to check the right config

**Comment by ClaudiaComito** [comment]
Debugging WIP:

|  CUDA  |   Procs   |  Nodes | Loop index |  Split  |
|--------|--------|--------|--------|--------|

**Comment by mrfh92** [comment]
(sry for all the commits ... I got a merge conflict in my local repository and had to repair it)

**Comment by mrfh92** [comment]
@ClaudiaComito @mtar Im currently doing a random search (2000 samples) on my workstation with 1-8 processes, (20-40) x (20-40) matrices (float32 on GPU), split=0,1, and tiles_per_proc=1,2 in order to detect possible further problematic configurations.

**Comment by mrfh92** [comment]
I have repeated this test with 500 samples, for 1-8 processes but only split=0 and tiles per proc = 1. 
Again, there are two kinds of errors: 

* wrong result, but programm completes 

* program does not complete due to an error: 

  *Test 128 of 500:*
  ```
  No protocol specified
  Traceback (most recent call last):
    File "qrtests.py", line 20, in <module>
      Q,R = ht.linalg.qr(A,tiles_per_proc=tiles_per_proc)
    File "/home/hopp_fa/heat/heat/core/linalg/qr.py", line 146, in qr
      __split0_r_calc(
    File "/home/hopp_fa/heat/heat/core/linalg/qr.py", line 354, in __split0_r_calc
      q1, r1 = torch.linalg.qr(base_tile, mode="complete")
  TypeError: linalg_qr(): argument 'A' (position 1) must be Tensor, not NoneType
  Traceback (most recent call last):
    File "qrtests.py", line 20, in <module>
      Q,R = ht.linalg.qr(A,tiles_per_proc=tiles_per_proc)
    File "/home/hopp_fa/heat/heat/core/linalg/qr.py", line 146, in qr
      __split0_r_calc(
    File "/home/hopp_fa/heat/heat/core/linalg/qr.py", line 392, in __split0_r_calc
      __split0_merge_tile_rows(
    File "/home/hopp_fa/heat/heat/core/linalg/qr.py", line 524, in __split0_merge_tile_rows
      lower_inds = r_tiles.get_start_stop(key=(lower_row, column))
    File "/home/hopp_fa/heat/heat/core/tiling.py", line 853, in get_start_stop
      pr = self.tile_map[key][..., 2].unique()
  IndexError: index 5 is out of bounds for dimension 0 with size 5
  ```

**Comment by mtar** [comment]
Thanks, may I have the python script you used for testing?

**Comment by mrfh92** [comment]
Actually, these are two scripts: 

* the outer loop: 
  ```
  from IPython import get_ipython
  import os 
  import numpy as np 
  
  n_samples = 500
  
  for it in range(n_samples):
      print(f"Test {it} of {n_samples}")
      n_procs = np.random.randint(1,9)
      m = np.random.randint(20,41)
      n = np.random.randint(20,41)
      split = 0 #np.random.randint(0,2)
      tiles = 1 #np.random.randint(1,3)
  
      os.environ["QR_NO"]="%d"%it
      os.environ["QR_M"]="%d"%m
      os.environ["QR_N"]="%d"%n
      os.environ["QR_SPLIT"]="%d"%split
      os.environ["QR_TILES"]="%d"%tiles
  
      ip = get_ipython() 
      ip.run_cell(f"! mpirun -n {n_procs} python -W ignore qrtests.py")
  
      failure = os.getenv("QR_FAILURE")
      print(failure)
  ```
* and the inner programm:  
  ```
  import heat as ht 
  import os
  
  no = int(os.getenv("QR_NO"))
  m = int(os.getenv("QR_M"))
  n = int(os.getenv("QR_N"))
  split = int(os.getenv("QR_SPLIT"))
  tiles_per_proc = int(os.getenv("QR_TILES"))
  
  dtype = ht.float32
  device="gpu"
  
  A = ht.random.randn(m,n,split=split,dtype=dtype,device=device)
  
  if A.comm.rank == 0:
      normalfile = open('tested_configs.txt', 'a')
      print(f'{no}: {m} x {n} matrix on {ht.MPI_WORLD.size} procs, split = {split} and {tiles_per_proc} tiles per proc.',file=normalfile)
      normalfile.close()
  
  Q,R = ht.linalg.qr(A,tiles_per_proc=tiles_per_proc)
  
  noerror = ht.allclose((A.resplit(Q.split) - (Q @ R)), 0, rtol=1e-5, atol=1e-5) and ht.allclose(Q.T @ Q, ht.eye(m,device=device,split=Q.T.split), rtol=1e-5, atol=1e-5) and ht.allclose(ht.eye(m,device=device,split=Q.split), Q @ Q.T, rtol=1e-5, atol=1e-5)
  
  if A.comm.rank == 0:
      if not noerror: 
          errorfile = open('failures_config.txt', 'a')
          print(f'{no}: {m} x {n} matrix on {ht.MPI_WORLD.size} procs, split = {split} and {tiles_per_proc} tiles per proc.',file=errorfile)
          errorfile.close()
  ```

**Comment by mrfh92** [comment]
Update: One can speed this up with the help of ray, e.g., as follows: 

```
import heat as ht 
import os
import argparse

parser = argparse.ArgumentParser(description="Test the QR implementation in HEAT")

# Add arguments
parser.add_argument("-m", type=int, help="number of rows for test matrix", required=True)
parser.add_argument("-n", type=int, help="number of columns for test matrix", required=True)
parser.add_argument("-split", type=int, help="split dimension for test matrix", required=True)
parser.add_argument("-tiles", type=int, help="tiles per process in the QR decomposition", required=True)

# Parse the arguments
args = parser.parse_args()


m = args.m
n = args.n
split = args.split
tiles_per_proc = args.tiles

dtype = ht.float32
device="gpu"

A = ht.random.randn(m,n,split=split,dtype=dtype,device=device)

if A.comm.rank == 0:
    normalfile = open('tested_configs.txt', 'a')
    print(f'{m} x {n} matrix on {ht.MPI_WORLD.size} procs, split = {split} and {tiles_per_proc} tiles per proc.',file=normalfile)
    normalfile.close()

Q,R = ht.linalg.qr(A,tiles_per_proc=tiles_per_proc)

noerror = ht.allclose((A.resplit(Q.split) - (Q @ R)), 0, rtol=1e-5, atol=1e-5) and ht.allclose(Q.T @ Q, ht.eye(m,device=device,split=Q.T.split), rtol=1e-5, atol=1e-5) and ht.allclose(ht.eye(m,device=device,split=Q.split), Q @ Q.T, rtol=1e-5, atol=1e-5)

if A.comm.rank == 0:
    if not noerror: 
        errorfile = open('failures_config.txt', 'a')
        print(f'{m} x {n} matrix on {ht.MPI_WORLD.size} procs, split = {split} and {tiles_per_proc} tiles per proc.',file=errorfile)
        errorfile.close()
```

```
import ray
import subprocess
import numpy as np

# Initialize Ray
ray.init()

# Define a remote function
@ray.remote(num_gpus=0.125)
def run_script(params):
    # Call your Python script with MPI and other parameters
    n_procs = params[0]
    n = params[1]
    m = params[2]
    split = params[3]
    tiles = params[4]
    subprocess.run(f"mpirun -n {n_procs} python qrtests.py -n {n} -m {m} -split {split} -tiles {tiles}", shell=True)

# Number of runs
num_runs = 5000
parameter_space = [[np.random.randint(1,9), np.random.randint(20,41), np.random.randint(20,41), np.random.randint(0,2), np.random.randint(1,3)] for _ in range(num_runs)] 

# Generate a random number of processes for each run and set parameters
futures = [run_script.remote(params) for params in parameter_space]

# Execute the script
# If your script returns results, you can gather them
results = ray.get(futures)
```

**Comment by mrfh92** [comment]
Additional errors: 

* wrong result, but programm runs through: 
```
44 x 54 matrix on 2 procs, split = 0 and 1 tiles per proc.
52 x 32 matrix on 3 procs, split = 0 and 1 tiles per proc.
```

* programm aborts withe error: 
```
47 x 43 matrix on 2 procs, split = 1 and 1 tiles per proc.
38 x 31 matrix on 12 procs, split = 0 and 1 tiles per proc.
```

**Comment by mrfh92** [comment]
Python script for Testing and Test results (configurations reproducing the error) are found in the Issue #1289 now.

**Pull request closed without merging**
