### PR TITLE
Update Heat Tutorials, fix typos.

### PR DESCRIPTION
**Pull request by LScheib**
## Due Diligence

- General:
    - [x]  **base branch** must be `main` for new features, latest release branch (e.g. `release/1.3.x`) for bug fixes
    - [x]  **title** of the PR is suitable to appear in the [Release Notes](https://github.com/helmholtz-analytics/heat/releases/latest)
- Implementation:
    - [x] unit tests: all split configurations tested
    - [x] unit tests: multiple dtypes tested
    - [x] documentation updated where needed

## Description

Issue resolved: #1235 
To get started with Heat I went through the [documentation](https://heat.readthedocs.io) and particularly the provided [tutorials](https://heat.readthedocs.io/en/stable/tutorials.html). While doing so, I noticed a few minor linguistic mistakes and typos in code snippets, which I correct here. Also I try to slightly improve the uniformity of the given code examples. 

#### Does this change modify the behaviour of other functions? If so, which?
no

### CODE REVIEW

**Review by mrfh92 — DISMISSED** [review]
Looks fine to me. 
Thanks :+1:

**Comment by mrfh92** [comment]
CI gets stuck again... this is strange since, e.g., #1236 did not get stuck

**Comment by mrfh92** [comment]
@mtar when youre fit again, can you have a look on this?

**Comment by ClaudiaComito** [comment]
I think the pipeline isn't triggering because `Receive PR` isn't triggered by changes in `doc/` (for good reasons). We should merge anyway.

**Review by ClaudiaComito — APPROVED** [review]
Thanks a lot @LScheib !!

**Pull request merged**
