### PR TITLE
DNDarray getitem: corrected split logic when ints in key

### PR DESCRIPTION
**Pull request by coquelin77**
## Description

Addressed getitem split bug

Issue/s resolved: #730 

## Changes proposed:
- change in logic for the new split calculation in getitem when ints are in the key

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## Due Diligence

- [x] All split configurations tested
- [x] Multiple dtypes tested in relevant functions
- [x] Documentation updated (if needed)
- [x] Updated changelog.md under the title "Pending Additions"

#### Does this change modify the behaviour of other functions? If so, which?
It might need change things which relied upon the buggy code. however the tests run clean, so hopefully this just wasnt noticed previously.

### CODE REVIEW

**Review by mtar — APPROVED** [review]

**Review by ClaudiaComito — APPROVED** [review]
Great, thanks for this.
I've fixed the problem for reductions operations in #744.

**Review by ClaudiaComito — CHANGES_REQUESTED** [review]
@coquelin77 I just realized  both #730 fixes  (#732 and former #744) must branch off 0.5.x, not off the main branch. We can then release the bug fixes right away without waiting for 0.6.0.

**Comment by ClaudiaComito** [comment]
> @coquelin77 I just realized both #730 fixes (#732 and former #744) must branch off 0.5.x, not off the main branch. We can then release the bug fixes right away without waiting for 0.6.0.

Alright, I think I'm taking this back. The #744 fix already uses some of the 0.6 features and I'm not sure walking the code back to 0.5 state is worth the time. I'll reopen #744 as is and reapprove this one as is as well.

**Review by ClaudiaComito — DISMISSED** [review]

**Comment by coquelin77** [comment]
the master merge cleared the approval from @ClaudiaComito but i dont think that we need to go through it again. i will merge it once the tests run throguh

**Pull request merged**
