### PR TITLE
GitHub Workflow integration

### PR DESCRIPTION
**Pull request by TheSlimvReal**
## Description

GitHub recently introduced the new GitHub Actions and the GitHub Workflow. 
These two features allow to create a build pipeline directly in GitHub with many useful features.
For the moment I was able to recreate the old Travis CI pipeline with more readability.

The build and unittest reports can now be viewed directly in GitHub and each number of processes has it's own report. This way it's easy to see if only for some number of processes the build fails.
Added to that I also created two new Docker images. The first one is based on the old one and uses Fedora. The second one is based on Ubuntu which works a little bit different. I think it's a good practice to have our code tested on both operating systems.

Please leave some comments with your opinions about the new [GitHub Actions logs](https://github.com/helmholtz-analytics/heat/commit/58cf0ca55b08530e75c0e5bea6ee754a088c5344/checks?check_suite_id=351707176).
Do you think this is useful for further usages?

Implements: #424 

Changes proposed:
- Moved CI to GitHub Actions
- Created new Docker images
- Testing is performed on Fedora and Ubuntu
- Travis is removed

## Type of change

Select relevant options.

[ ] Bug fix (non-breaking change which fixes an issue)
[x] New feature (non-breaking change which adds functionality)
[ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
[ ] Documentation update

Are all split configurations tested and accounted for?
[x] yes [ ] no
Does this change require a documentation update outside of the changes proposed?
[ ] yes [x] no
Does this change modify the behaviour of other functions?
[ ] yes [x] no
Are there code practices which require justification?
[ ] yes [x] no

### CODE REVIEW

**Comment by mtar** [comment]
There seems to be a problem in Upload Codevoc [sic] in the ubuntu workflows.

**Comment by mtar** [comment]
It would be nice to have workflows without the optional dependencies hdf5 and netcdf.

**Comment by TheSlimvReal** [comment]
> There seems to be a problem in Upload Codevoc [sic] in the ubuntu workflows.

Thanks for the info, I fixed that

> It would be nice to have workflows without the optional dependencies hdf5 and netcdf.

What do you mean? Start additional test runs without installing the `netcdf` and the `hdf5` dependencies?

**Comment by mtar** [comment]
> What do you mean? Start additional test runs without installing the netcdf and the hdf5 dependencies?

Yes, something like that.

**Comment by ClaudiaComito** [comment]
@TheSlimvReal Simon, I've tried to recreate one of the most annoying Travis failures (time out) without success :/ I'm going to pull this branch into my working branch so I can test it while I work on other things.

In general, I like the GitHub Workflow a lot better than our current setup, more information and faster feedback, as far as I'm concerned it's definitely an improvement. Thanks a lot!

**Comment by TheSlimvReal** [comment]
I now added another dimension to the build matrix which toggles the optional dependencies to `netcdf` and `hdf5`

**Pull request closed without merging**
