### PR TITLE
Binary special methods return NotImplemented

### PR DESCRIPTION
**Pull request by mtar**
## Due Diligence

- General:
    - [x]  **base branch** must be `main` for new features, latest release branch (e.g. `release/1.3.x`) for bug fixes
    - [x]  **title** of the PR is suitable to appear in the [Release Notes](https://github.com/helmholtz-analytics/heat/releases/latest)
- Implementation:
    - [x] unit tests: all split configurations tested
    - [x] unit tests: multiple dtypes tested
    - [x] documentation updated where needed

## Description

This Pull Request adds special functions for binary arithmetic operations to DNDarray, such that they return NotImplemented on unsupported inputs.

Issue/s resolved: #311, #958 (partially)

## Changes proposed:
- define special methods emulating number types on binary arithmetic operations and reflected ones https://docs.python.org/3/reference/datamodel.html#emulating-numeric-types
- add divmod()

## Type of change
Enhancement

#### Does this change modify the behaviour of other functions? If so, which?
yes / no

### CODE REVIEW

**Review by mrfh92 — DISMISSED** [review]
As far as I can judge, these changes look fine :+1: 
Consequently, I recommend merging if all tests run through. 
Thanks for your work :)

**Comment by mrfh92** [comment]
There seems to be a problem with PyTorch==1.8.1 and PyTorch==1.9.1

**Review by ClaudiaComito — DISMISSED** [review]
Thanks a lot @mtar, looks great except for the backward compatibility with older Pytorch versions (1.8, 1.9). Once that's solved, we can merge.

**Review by mrfh92 — APPROVED** [review]
Changes to ensure backward compatibility look fine. If the CI runs through I now approve merging.

**Comment by mrfh92** [comment]
needed to dismuss @ClaudiaComito to trigger backward-compatibility checks to see whether my requested changes are now satisfied

**Comment by mrfh92** [comment]
Its still failing so I retracted my review

**Review by mrfh92 — APPROVED** [review]
fine :+1:

**Review by ClaudiaComito — CHANGES_REQUESTED** [review]

**Review by mrfh92 — APPROVED** [review]
Last changes in the docs look fine. I recommend merging if the test run through. 
Thx for the work :+1:

**Pull request merged**
