### PR TITLE
Features/1563 Add Dynamic Mode Decomposition (DMD)

### PR DESCRIPTION
**Pull request by mrfh92**
## Due Diligence

- General:
    - [X]  **title** of the PR is suitable to appear in the [Release Notes](https://github.com/helmholtz-analytics/heat/releases/latest)
- Implementation:
    - [x] unit tests: all split configurations tested
    - [x] unit tests: multiple dtypes tested
    - [ ] ~~benchmarks: created for new functionality~~ (does not really make sense as DMD is mainly a wrapper for several linalg routines that should be benchmarked instead?) 
    - [ ] benchmarks: performance improved or maintained
    - [x] documentation updated where needed

## Description

Issue/s resolved: #1563 

## Type of change
New feature (non-breaking change which adds functionality)

#### Does this change modify the behaviour of other functions? If so, which?
no

### CODE REVIEW

**Comment by mrfh92** [comment]
todo: think about what `.predict` should do

**Comment by mrfh92** [comment]
interesting to know: on AMD, calculation of the singular values is about one digit less accurate than on Nvidia for one of the cases tested here

**Comment by mrfh92** [comment]
incremental SVD should be merged first

**Comment by JuanPedroGHM** [comment]
### Benchmarks results - Sponsored by [perun](https://github.com/Helmholtz-AI-Energy/perun)

| function                 |   mpi_ranks | device   | metric   |      value |   ref_value |         std |   % change | type            | alert   |   lower_quantile |   upper_quantile |
|--------------------------|-------------|----------|----------|------------|-------------|-------------|------------|-----------------|---------|------------------|------------------|
| matmul_split_0           |           4 | CPU      | RUNTIME  | 0.154507   |  0.181238   | 0.0301997   |  -14.7489  | jump-detection  | True    |      nan         |      nan         |
| matmul_split_1           |           4 | CPU      | RUNTIME  | 0.136998   |  0.114562   | 0.0342437   |   19.5839  | jump-detection  | True    |      nan         |      nan         |
| apply_inplace_normalizer |           4 | CPU      | RUNTIME  | 0.00474786 |  0.00104532 | 0.0112784   |  354.2     | jump-detection  | True    |      nan         |      nan         |
| matmul_split_0           |           4 | GPU      | RUNTIME  | 0.0456438  |  0.0562632  | 0.0391694   |  -18.8744  | jump-detection  | True    |      nan         |      nan         |
| matmul_split_1           |           4 | GPU      | RUNTIME  | 0.0230197  |  0.0343244  | 0.00679629  |  -32.9349  | jump-detection  | True    |      nan         |      nan         |
| concatenate              |           4 | GPU      | RUNTIME  | 0.161198   |  0.142046   | 0.0437837   |   13.4829  | jump-detection  | True    |      nan         |      nan         |
| matmul_split_1           |           4 | CPU      | RUNTIME  | 0.136998   |  0.116819   | 0.0342437   |   17.2733  | trend-deviation | True    |        0.103781  |        0.133401  |
| qr_split_1               |           4 | CPU      | RUNTIME  | 0.17927    |  0.186863   | 0.00593083  |   -4.06355 | trend-deviation | True    |        0.179407  |        0.196056  |
| lanczos                  |           4 | CPU      | RUNTIME  | 0.242476   |  0.246717   | 0.00199095  |   -1.71872 | trend-deviation | True    |        0.243013  |        0.252841  |
| hierachical_svd_tol      |           4 | CPU      | RUNTIME  | 0.0513822  |  0.0521396  | 0.000303397 |   -1.45264 | trend-deviation | True    |        0.0515701 |        0.0531136 |
| reshape                  |           4 | CPU      | RUNTIME  | 0.156436   |  0.160234   | 0.00119464  |   -2.37053 | trend-deviation | True    |        0.156578  |        0.167456  |
| qr_split_0               |           4 | GPU      | RUNTIME  | 0.0493844  |  0.0560393  | 0.0024326   |  -11.8755  | trend-deviation | True    |        0.050371  |        0.0655274 |
| hierachical_svd_tol      |           4 | GPU      | RUNTIME  | 0.122547   |  0.119621   | 0.00434382  |    2.44577 | trend-deviation | True    |        0.117207  |        0.122445  |
| kmeans                   |           4 | GPU      | RUNTIME  | 0.677463   |  0.646702   | 0.00220415  |    4.75664 | trend-deviation | True    |        0.623644  |        0.677172  |

[Grafana Dashboard](http://57bc8d92-72f2-4869-accd-435ec06365cb.ka.bw-cloud-instance.org:3000/d/adjpqduq9r7k0a/heat-cb?orgId=1)
Last updated: 2024-11-15T12:05:15Z

**Review by Hakdag97 — APPROVED** [review]

**Pull request merged**
