### PR TITLE
Fixed torch 1.6.0 printing

### PR DESCRIPTION
**Pull request by Markus-Goetz**
## Description

Fixed tensor printing issues with torch 1.6.0

Issue/s resolved: #647

## Changes proposed:
- Torch 1.6.0 switches the order of two parameters, respective version check implemented and call-through with corresponding parameter order

## Due Diligence

- [x] All split configurations tested
- [x] Multiple dtypes tested in relevant functions
- [x] Documentation updated (if needed)
- [x] Updated changelog.md under the title "Pending Additions"

#### Does this change modify the behaviour of other functions? If so, which?
no

### CODE REVIEW

**Comment by mtar** [comment]
c9269bc3cb9a5bff97609d10cfe9da0f9c4c3495 conflicts with #653

**Comment by coquelin77** [comment]
> [c9269bc](https://github.com/helmholtz-analytics/heat/commit/c9269bc3cb9a5bff97609d10cfe9da0f9c4c3495) conflicts with #653

**Comment by mtar** [comment]
Can one of the admins verify this patch?

**Comment by coquelin77** [comment]
@mtar how does this conflict? is there an inconsistency between the torch argmax / argmin and np argmax / argmin?

**Comment by coquelin77** [comment]
this is being merged. another PR is handling the `argmin` and `argmax` changes for 1.6.0

**Pull request merged**
