### PR TITLE
Provide TL;DR for new contributors

### PR DESCRIPTION
**Pull request by ClaudiaComito**
[@Mystic-Slice @shahpratham @mrfh92 @bducos I got started on issue #1051 . This is a just a draft, we'd love your input on both content and format, feel free to comment here or commit changes. Of course @AmirTouilPU  @neosunhan @saisuraj27-729 @tewodros18 feel free to chime in, if you have time.]  

## Description

Provide quick hands-on instructions for new contributors, in preparation for GSoC23. 
Still TODO:
- add FAQ 
- coordinate with content in [Contributing](contributing.md)
- even better: TL;DR on README should be a list of links to [Contributing](contributing.md) sections
- add a script  to test MPI environment e.g. `mpirun -n 2 python test_script.py`
- DOs and DON'Ts just a placeholder for now, need a more welcoming format
- ...??
- maybe add a short help regarding authetification (set up of ssh etc.)

Issue/s resolved: #1051 

## Changes proposed:
-
-
-
-

## Type of change

- Documentation update
## Memory requirements

NA
## Performance

NA

## Due Diligence
- [ ] All split configurations tested
- [ ] Multiple dtypes tested in relevant functions
- [ ] Documentation updated (if needed)
- [ ] Title of PR is suitable for corresponding CHANGELOG entry

#### Does this change modify the behaviour of other functions? If so, which?
no

### CODE REVIEW

**Comment by shahpratham** [comment]
Hey @ClaudiaComito ,
I think we should add this in `Contributing.md` and should mention at start a small TL;DR and can add its link to README.

For adding test_script, we can include 1 process sending a random number to other or just "hello world" from both process

> maybe add a short help regarding authetification (set up of ssh etc.)

We can maybe link to [this](https://docs.github.com/en/authentication/troubleshooting-ssh)

**Comment by ClaudiaComito** [comment]
Guys, sorry for putting on my God Hat and bypassing the review process, GSoC23 enquiries are already pouring in. Our [Quick Start](https://github.com/helmholtz-analytics/heat) is now live.

It still needs improvements so I'll leave this PR draft open. 

Feel free to commit any modification you think necessary. We will review and potentially merge changes every week.

**Comment by Hmm-its-me** [comment]
Hi, everyone. I found that a few changes can be made to our README file to make it more better and useful for first-time viewers. After seeing the readme files of Tensorflow, Numpy...etc I made some changes to make our README file look better and more useful, I created a [PR](https://github.com/helmholtz-analytics/heat/pull/1079)  with those changes, any suggestions are welcome. So, you can merge it if you find it good. Also, please tell me if you want me to make any more changes to it, Thank you.

**Comment by ClaudiaComito** [comment]
superseded by #1079 , closing

**Pull request closed without merging**
