### PR TITLE
Distributed Compressed Sparse Column Matrix

### PR DESCRIPTION
**Pull request by Mystic-Slice**
## Due Diligence

- General:
    - [x]  **title** of the PR is suitable to appear in the [Release Notes](https://github.com/helmholtz-analytics/heat/releases/latest)
- Implementation:
    - [x] unit tests: all split configurations tested
    - [x] unit tests: multiple dtypes tested
    - [x] documentation updated where needed

## Description

A new format similar to the one implemented in https://github.com/helmholtz-analytics/heat/pull/1028.

Most code from the previous implementation is common for both formats.

Steps:

- [x] Implement a common base class
- [x] Factory methods
- [x] Sparse and Dense formats interconversion
- [x] Arithmetic Operations
- [x] Tests

**NOTE:** In the future, when arithmetic operations are supported by `torch` for `sparse_csc`, they can be enabled for `DCSC_matrix` by restoring the code removed in commit https://github.com/helmholtz-analytics/heat/pull/1377/commits/6d727affd5c9cff63f84896e2c8e77fcfe042335. The binary operator has already been modified to be generic for both `DCSR_matrix` and `DCSC_matrix`.

## Type of change

New feature

### CODE REVIEW

**Comment by Mystic-Slice** [comment]
I just discovered something that I should have seen a long time ago.

`torch` only officially supports the `matmul` operation for its CSR and CSC formats. (https://pytorch.org/docs/stable/sparse.html#csr-tensor-operations)
The elementwise operations (`add` and `mul`) are implemented for CSR(although not mentioned in their docs) but not for CSC.

It is still possible for us to implement `matmul` for `ht.sparse` module. Just wanted to know how we should proceed.

**Comment by ClaudiaComito** [comment]
> I just discovered something that I should have seen a long time ago.
> 
> `torch` only officially supports the `matmul` operation for its CSR and CSC formats. (https://pytorch.org/docs/stable/sparse.html#csr-tensor-operations) The elementwise operations (`add` and `mul`) are implemented for CSR(although not mentioned in their docs) but not for CSC.
> 
> It is still possible for us to implement `matmul` for `ht.sparse` module. Just wanted to know how we should proceed.

@Mystic-Slice thank you so much for this and apologies for the delay.

It's OK not to provide the element-wise operations for CSC if torch doesn't implement them yet. 

The basic operation we want to be able to provide with this class, is matrix multiplication CSR @ CSC, when 
CSR is distributed (split=0) and CSC is not distributed. This operation requires no MPI communication, returns a distributed CSR. It would be a great starting point, and it doesn't need to be part of this PR. 


Is this PR, the CSC class, ready for review @Mystic-Slice ? 

Thanks again, we highly appreciate your contribution!

**Comment by Mystic-Slice** [comment]
Hi @ClaudiaComito 
Sorry for the delay from my side too.
The implementation of DCSC_matrix is complete. I just need to write a few tests.
I will complete them asap.

If tests aren't a blocker for review, we can proceed with that.

**Comment by ClaudiaComito** [comment]
> Hi @ClaudiaComito Sorry for the delay from my side too. The implementation of DCSC_matrix is complete. I just need to write a few tests. I will complete them asap.
> 
> If tests aren't a blocker for review, we can proceed with that.

Hi @Mystic-Slice, thanks, the tests make the review so much easier, so please go ahead and sketch the tests first.  Thanks a lot!

**Comment by Mystic-Slice** [comment]
@ClaudiaComito The tests are done.

**Comment by Mystic-Slice** [comment]
PR is ready for review

**Comment by Mystic-Slice** [comment]
In the future, when arithmetic operations are supported by `torch` for `sparse_csc`, they can be enabled for `DCSC_matrix` by restoring the code removed in commit https://github.com/helmholtz-analytics/heat/commit/6d727affd5c9cff63f84896e2c8e77fcfe042335. The binary operator has already been modified to be generic for both `DCSR_matrix` and `DCSC_matrix`.

**Comment by ClaudiaComito** [comment]
Waiting on #1443 (solves `test_random` failure on AMD runner among other things)

**Comment by Mystic-Slice** [comment]
I was able to recreate this error on my local machine.
It occurs when the torch and torchvision version do not match. 
In my case, specifically, `torch==2.2` and `torchvision==0.18.0` (which corresponds to `torch==2.3`).
When I made the versions match, they work perfectly fine.

I believe the torch version on cuda runner is 2.2 and not 2.3. But I am not sure.
image

Is there a way to check that?

**Comment by ClaudiaComito** [comment]
> I was able to recreate this error on my local machine. It occurs when the torch and torchvision version do not match. In my case, specifically, `torch==2.2` and `torchvision==0.18.0` (which corresponds to `torch==2.3`). When I made the versions match, they work perfectly fine.
> 
> I believe the torch version on cuda runner is 2.2 and not 2.3. But I am not sure. image
> 
> Is there a way to check that?

@mtar can you look into this? thanks

**Comment by ClaudiaComito** [comment]
@Mystic-Slice this looks amazing. Will you add your name to the [CITATION.cff file](https://github.com/helmholtz-analytics/heat/blob/sparse_csc/CITATION.cff), under the `# release contributors - add as needed` header?  Thanks!

**Comment by Mystic-Slice** [comment]
Done!

**Review by ClaudiaComito — DISMISSED** [review]
Amazing work @Mystic-Slice ! 👏🏼

**Comment by ClaudiaComito** [comment]
@Mystic-Slice one single test fails with torch<2, see below. From my side it's absolutely OK to skip the test when torch<2

```
_________________________ TestDCSC_matrix.test_astype __________________________

self = <heat.sparse.tests.test_dcscmatrix.TestDCSC_matrix testMethod=test_astype>

    def test_astype(self):
        heat_sparse_csc = ht.sparse.sparse_csc_matrix(self.ref_torch_sparse_csc)
    
        # check starting invariant
        self.assertEqual(heat_sparse_csc.dtype, ht.float32)
    
        # check the copy case for uint8
>       as_uint8 = heat_sparse_csc.astype(ht.uint8)

heat/sparse/tests/test_dcscmatrix.py:273: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = , dtype = <class 'heat.core.types.uint8'>, copy = True

    def astype(self, dtype, copy=True) -> __DCSX_matrix:
        """
        Returns a casted version of this matrix.
        Casted matrix is a new matrix of the same shape but with given type of this matrix. If copy is ``True``, the
        same matrix is returned instead.
    
        Parameters
        ----------
        dtype : datatype
            HeAT type to which the matrix is cast
        copy : bool, optional
            By default the operation returns a copy of this matrix. If copy is set to ``False`` the cast is performed
            in-place and this matrix is returned
        """
        dtype = canonical_heat_type(dtype)
>       casted_matrix = self._array.type(dtype.torch_type())
E       RuntimeError: torch.copy_: only sparse compressed tensors with the same number of specified elements are supported.

heat/sparse/dcsx_matrix.py:309: RuntimeError
```

**Comment by Mystic-Slice** [comment]
@ClaudiaComito 
Seems like the `.type()` doesnt support conversion of a lot of Tensor types. I should have used `.to()` method instead.
Made the change.

**Review by ClaudiaComito — APPROVED** [review]
Thanks @Mystic-Slice ! (take 2)

**Comment by Mystic-Slice** [comment]
Seems like it didnt work
I will just skip the test for `torch < 2.0`.
Sorry for the delay. I thought the previous fix would work.

**Review by ClaudiaComito — APPROVED** [review]
Take 3!

**Pull request merged**
