### PR TITLE
Bug/73 broadcast of   binop

### PR DESCRIPTION
**Pull request by krajsek**
This pull request will solve several issues in situations where there are more MPI ranks than the range of the spit dimension.

In particular:

Commit will fix the case tensor.comm.size>shape[tensor.split]  in function  __binary_op
in file operations.py

The original   __binary_op  will fail in case of broadcasing 
when there are ranks with empty tensors. In this case tensors are 
fetched from the the rank 0 process if needed. In case a rank contains an empty
tensor the operation will be skipped.
 
Commit will fix load_hdf5 for  tensor.comm.size>shape[tensor.split] in io.py

### CODE REVIEW

**Comment by Cdebus** [comment]
Hey, I also ran across this problem (in kmeans), thanks for the fix!

**Comment by Markus-Goetz** [comment]
Bump, requires merge of master

**Comment by Markus-Goetz** [comment]
Looks good to me.

Do we want to keep the redistribution warning where it is right now, or move it to resplit()?

**Comment by krajsek** [comment]
> 
> 
> Looks good to me.
> 
> Do we want to keep the redistribution warning where it is right now, or move it to resplit()?

I would keep it there.

**Pull request merged**
