### PR TITLE
Documentation updates after new release

### PR DESCRIPTION
**Pull request by ClaudiaComito**
## Due Diligence

- General:
    - [x]  **title** of the PR is suitable to appear in the [Release Notes](https://github.com/helmholtz-analytics/heat/releases/latest)
- Implementation:
    - [ ] unit tests: all split configurations tested
    - [ ] unit tests: multiple dtypes tested
    - [ ] benchmarks: created for new functionality
    - [ ] benchmarks: performance improved or maintained
    - [ ] documentation updated where needed

## Description

Issue/s resolved: #1186 

## Changes proposed:

- updated Requirements section on README
- updated RELEASE.md to match current workflow

## Type of change

- Documentation update
#### Does this change modify the behaviour of other functions? If so, which?
no

### CODE REVIEW

**Review by mtar — APPROVED** [review]

**Comment by ClaudiaComito** [comment]
@mtar not sure we should backport this one.

**Comment by mtar** [comment]
The documentation yes, the version not

**Comment by ClaudiaComito** [comment]
@mtar  removed the version update from this PR

**Review by mrfh92 — APPROVED** [review]
Looks fine. Thanks @ClaudiaComito for updating 👍

**Pull request merged**
