### PR TITLE
Fixed install command in readme

### PR DESCRIPTION
**Pull request by rainman110**
## Description

The installation command contained spaces, which at least my pip didn't like.

## Type of change

- Documentation update

#### Does this change modify the behaviour of other functions? If so, which?
no

### CODE REVIEW

**Comment by coquelin77** [comment]
do we need to remove these spaces? does that do something different? i thought that they were ignored by the interpreter

**Comment by rainman110** [comment]
Using spaces, I had trouble with the installation. So yes, it seems to be required.

**Comment by mtar** [comment]
I can confirm that. The spaces are problematic on bash.

**Comment by coquelin77** [comment]
thanks for the confirmation @mtar ill update this branch and merge it today

**Review by coquelin77 — APPROVED** [review]

**Pull request merged**
