### PR TITLE
Features/67 tuple axis

### PR DESCRIPTION
**Pull request by ClaudiaComito**
Looking to address Issue #67

### CODE REVIEW

**Comment by Markus-Goetz** [comment]
Small merge conflict with master. Bump

**Comment by ClaudiaComito** [comment]
Merged latest master.

**Comment by ClaudiaComito** [comment]
Oh yes, that looks bad! I'll look into it.

**Comment by ClaudiaComito** [comment]
OK thanks for catching this Markus! Allreduce wasn't being triggered if axis was a tuple because the condition (axis == x.split) was never verified. I've fixed this now, fixed the tests, and added a check to test_sum to verify that Allreduce is triggered.

> I guess the expected solution would be:
> 
> ```
> mpirun --tag-output -np 2 python foo.py
> [1,0]<stdout>:tensor([[[12., 12., 12., 12., 12.]]]) (5,) (5,) None
> [1,1]<stdout>:tensor([[[12., 12., 12., 12., 12.]]]) (5,) (5,) None
> ```

This is what I get now:
```
tensor([[[12., 12., 12., 12., 12.]]]) (5,) (1, 1, 5) None
tensor([[[12., 12., 12., 12., 12.]]]) (5,) (1, 1, 5) None
```

We've got keepdim=True by default when calculating partial locally, so I do expect lshape to keep the reduced dimensions. Should that be changed?

**Comment by Markus-Goetz** [comment]
This is awesome. Thanks for fixing it. 

Yes, I do think the local shape should be the same as the gshape in these cases. By default numpy does not do a keepdim (even though we wrongly did so initially). I think having a keepdim=False default should be generally the way to go, also for the other operations.

**Comment by ClaudiaComito** [comment]
> 
> Yes, I do think the local shape should be the same as the gshape in these cases. By default numpy does not do a keepdim (even though we wrongly did so initially). I think having a keepdim=False default should be generally the way to go, also for the other operations.


I suggest we make this into a separate Issue if you don't mind. It'll break quite a few tests :)

**Comment by Markus-Goetz** [comment]
Fair enough. Would you please create it and reference it here as soon as you did? Beyond that, I will start the review again :).

**Comment by ClaudiaComito** [comment]
> Fair enough. Would you please create it and reference it here as soon as you did? Beyond that, I will start the review again :).

Done, see above. Thanks!

**Pull request merged**
